name: "Automatic Release"
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions: write-all
    name: "Make Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Compress"
        run: zip -r LatamResourcePack.zip assets pack.mcmeta
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Resource Pack Version"
          files: |
            *.zip
      